### ISSUE TITLE
Challenge not loading

### ISSUE THREAD

**Issue by wizrares** [raboof/learnyouacity#1]
I've tried playing on http://learnyouacity.herokuapp.com/ and the challenge doesn't start. I just says Play! and then Current challenge: remains blank. Am I doing something wrong?

**Comment by raboof** [comment]
Did you select a playing field with shift-drag? After some delay that should start the challenge.

Perhaps you chose an area that was too big?

**Comment by wizrares** [comment]
Ah, yes. I did not shift-click. Thank you for your reply :)

On Wed, Dec 4, 2013 at 9:35 AM, Arnout Engelen notifications@github.comwrote:

> Did you select a playing field with shift-drag? After some delay that
> should start the challenge.
> 
> Perhaps you chose an area that was too big?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/raboof/learnyouacity/issues/1#issuecomment-29790807
> .

## 

Life is not the amount of times you breathe, is the moments that take your
breath away.

To all things comes an end. And to all things comes a beginning.

Cred in inspirat, nu in expirat. in vise, nu in somn. In trait, nu in
existat.

**Comment by raboof** [comment]
No problem glad to hear you got it working!

I need to improve the interface because indeed this is not very obvious/user-friendly yet :). Also wondering how to select the playing field on mobile devices, shift-click is a bit of a no-go there of course :)

**Comment by ghost** [comment]
shift-clicking seems to become impossible if the first attempt was too large an area, after the 'try again' dialogue box is closed.

**Comment by raboof** [comment]
> shift-clicking seems to become impossible if the first attempt was too large an area, after the 'try again' dialogue box is closed.

Interesting! That seems like a different issue though - perhaps open a new item for that? Would you be interested in looking into fixing it?
